package com.test.entity;

public class MonConfigPoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_configuration_point.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_configuration_point.svg_id
     *
     * @mbggenerated
     */
    private String svgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_configuration_point.point_code
     *
     * @mbggenerated
     */
    private String pointCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_configuration_point.point_name
     *
     * @mbggenerated
     */
    private String pointName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_configuration_point.data_type
     *
     * @mbggenerated
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_configuration_point.data_unit
     *
     * @mbggenerated
     */
    private String dataUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_configuration_point.ds_code
     *
     * @mbggenerated
     */
    private String dsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_configuration_point.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_configuration_point.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_configuration_point.modify_time
     *
     * @mbggenerated
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_configuration_point.modify_user
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_configuration_point.id
     *
     * @return the value of mon_configuration_point.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_configuration_point.id
     *
     * @param id the value for mon_configuration_point.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_configuration_point.svg_id
     *
     * @return the value of mon_configuration_point.svg_id
     *
     * @mbggenerated
     */
    public String getSvgId() {
        return svgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_configuration_point.svg_id
     *
     * @param svgId the value for mon_configuration_point.svg_id
     *
     * @mbggenerated
     */
    public void setSvgId(String svgId) {
        this.svgId = svgId == null ? null : svgId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_configuration_point.point_code
     *
     * @return the value of mon_configuration_point.point_code
     *
     * @mbggenerated
     */
    public String getPointCode() {
        return pointCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_configuration_point.point_code
     *
     * @param pointCode the value for mon_configuration_point.point_code
     *
     * @mbggenerated
     */
    public void setPointCode(String pointCode) {
        this.pointCode = pointCode == null ? null : pointCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_configuration_point.point_name
     *
     * @return the value of mon_configuration_point.point_name
     *
     * @mbggenerated
     */
    public String getPointName() {
        return pointName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_configuration_point.point_name
     *
     * @param pointName the value for mon_configuration_point.point_name
     *
     * @mbggenerated
     */
    public void setPointName(String pointName) {
        this.pointName = pointName == null ? null : pointName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_configuration_point.data_type
     *
     * @return the value of mon_configuration_point.data_type
     *
     * @mbggenerated
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_configuration_point.data_type
     *
     * @param dataType the value for mon_configuration_point.data_type
     *
     * @mbggenerated
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_configuration_point.data_unit
     *
     * @return the value of mon_configuration_point.data_unit
     *
     * @mbggenerated
     */
    public String getDataUnit() {
        return dataUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_configuration_point.data_unit
     *
     * @param dataUnit the value for mon_configuration_point.data_unit
     *
     * @mbggenerated
     */
    public void setDataUnit(String dataUnit) {
        this.dataUnit = dataUnit == null ? null : dataUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_configuration_point.ds_code
     *
     * @return the value of mon_configuration_point.ds_code
     *
     * @mbggenerated
     */
    public String getDsCode() {
        return dsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_configuration_point.ds_code
     *
     * @param dsCode the value for mon_configuration_point.ds_code
     *
     * @mbggenerated
     */
    public void setDsCode(String dsCode) {
        this.dsCode = dsCode == null ? null : dsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_configuration_point.create_time
     *
     * @return the value of mon_configuration_point.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_configuration_point.create_time
     *
     * @param createTime the value for mon_configuration_point.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_configuration_point.create_user
     *
     * @return the value of mon_configuration_point.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_configuration_point.create_user
     *
     * @param createUser the value for mon_configuration_point.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_configuration_point.modify_time
     *
     * @return the value of mon_configuration_point.modify_time
     *
     * @mbggenerated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_configuration_point.modify_time
     *
     * @param modifyTime the value for mon_configuration_point.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_configuration_point.modify_user
     *
     * @return the value of mon_configuration_point.modify_user
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_configuration_point.modify_user
     *
     * @param modifyUser the value for mon_configuration_point.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }
}