package com.test.entity;

public class MonDatasource {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.ds_code
     *
     * @mbggenerated
     */
    private String dsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.ds_name
     *
     * @mbggenerated
     */
    private String dsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.ds_type
     *
     * @mbggenerated
     */
    private String dsType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.db_type
     *
     * @mbggenerated
     */
    private String dbType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.db_address
     *
     * @mbggenerated
     */
    private String dbAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.table_name
     *
     * @mbggenerated
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.field_point
     *
     * @mbggenerated
     */
    private String fieldPoint;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.field_value
     *
     * @mbggenerated
     */
    private String fieldValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.field_timestamp
     *
     * @mbggenerated
     */
    private String fieldTimestamp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.opc_address
     *
     * @mbggenerated
     */
    private String opcAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.class_id
     *
     * @mbggenerated
     */
    private String classId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.moni_brand
     *
     * @mbggenerated
     */
    private String moniBrand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.moni_position
     *
     * @mbggenerated
     */
    private String moniPosition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.modify_time
     *
     * @mbggenerated
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_datasource.modify_user
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.id
     *
     * @return the value of mon_datasource.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.id
     *
     * @param id the value for mon_datasource.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.ds_code
     *
     * @return the value of mon_datasource.ds_code
     *
     * @mbggenerated
     */
    public String getDsCode() {
        return dsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.ds_code
     *
     * @param dsCode the value for mon_datasource.ds_code
     *
     * @mbggenerated
     */
    public void setDsCode(String dsCode) {
        this.dsCode = dsCode == null ? null : dsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.ds_name
     *
     * @return the value of mon_datasource.ds_name
     *
     * @mbggenerated
     */
    public String getDsName() {
        return dsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.ds_name
     *
     * @param dsName the value for mon_datasource.ds_name
     *
     * @mbggenerated
     */
    public void setDsName(String dsName) {
        this.dsName = dsName == null ? null : dsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.ds_type
     *
     * @return the value of mon_datasource.ds_type
     *
     * @mbggenerated
     */
    public String getDsType() {
        return dsType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.ds_type
     *
     * @param dsType the value for mon_datasource.ds_type
     *
     * @mbggenerated
     */
    public void setDsType(String dsType) {
        this.dsType = dsType == null ? null : dsType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.db_type
     *
     * @return the value of mon_datasource.db_type
     *
     * @mbggenerated
     */
    public String getDbType() {
        return dbType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.db_type
     *
     * @param dbType the value for mon_datasource.db_type
     *
     * @mbggenerated
     */
    public void setDbType(String dbType) {
        this.dbType = dbType == null ? null : dbType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.name
     *
     * @return the value of mon_datasource.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.name
     *
     * @param name the value for mon_datasource.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.username
     *
     * @return the value of mon_datasource.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.username
     *
     * @param username the value for mon_datasource.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.password
     *
     * @return the value of mon_datasource.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.password
     *
     * @param password the value for mon_datasource.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.db_address
     *
     * @return the value of mon_datasource.db_address
     *
     * @mbggenerated
     */
    public String getDbAddress() {
        return dbAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.db_address
     *
     * @param dbAddress the value for mon_datasource.db_address
     *
     * @mbggenerated
     */
    public void setDbAddress(String dbAddress) {
        this.dbAddress = dbAddress == null ? null : dbAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.table_name
     *
     * @return the value of mon_datasource.table_name
     *
     * @mbggenerated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.table_name
     *
     * @param tableName the value for mon_datasource.table_name
     *
     * @mbggenerated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.field_point
     *
     * @return the value of mon_datasource.field_point
     *
     * @mbggenerated
     */
    public String getFieldPoint() {
        return fieldPoint;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.field_point
     *
     * @param fieldPoint the value for mon_datasource.field_point
     *
     * @mbggenerated
     */
    public void setFieldPoint(String fieldPoint) {
        this.fieldPoint = fieldPoint == null ? null : fieldPoint.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.field_value
     *
     * @return the value of mon_datasource.field_value
     *
     * @mbggenerated
     */
    public String getFieldValue() {
        return fieldValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.field_value
     *
     * @param fieldValue the value for mon_datasource.field_value
     *
     * @mbggenerated
     */
    public void setFieldValue(String fieldValue) {
        this.fieldValue = fieldValue == null ? null : fieldValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.field_timestamp
     *
     * @return the value of mon_datasource.field_timestamp
     *
     * @mbggenerated
     */
    public String getFieldTimestamp() {
        return fieldTimestamp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.field_timestamp
     *
     * @param fieldTimestamp the value for mon_datasource.field_timestamp
     *
     * @mbggenerated
     */
    public void setFieldTimestamp(String fieldTimestamp) {
        this.fieldTimestamp = fieldTimestamp == null ? null : fieldTimestamp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.opc_address
     *
     * @return the value of mon_datasource.opc_address
     *
     * @mbggenerated
     */
    public String getOpcAddress() {
        return opcAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.opc_address
     *
     * @param opcAddress the value for mon_datasource.opc_address
     *
     * @mbggenerated
     */
    public void setOpcAddress(String opcAddress) {
        this.opcAddress = opcAddress == null ? null : opcAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.class_id
     *
     * @return the value of mon_datasource.class_id
     *
     * @mbggenerated
     */
    public String getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.class_id
     *
     * @param classId the value for mon_datasource.class_id
     *
     * @mbggenerated
     */
    public void setClassId(String classId) {
        this.classId = classId == null ? null : classId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.moni_brand
     *
     * @return the value of mon_datasource.moni_brand
     *
     * @mbggenerated
     */
    public String getMoniBrand() {
        return moniBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.moni_brand
     *
     * @param moniBrand the value for mon_datasource.moni_brand
     *
     * @mbggenerated
     */
    public void setMoniBrand(String moniBrand) {
        this.moniBrand = moniBrand == null ? null : moniBrand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.moni_position
     *
     * @return the value of mon_datasource.moni_position
     *
     * @mbggenerated
     */
    public String getMoniPosition() {
        return moniPosition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.moni_position
     *
     * @param moniPosition the value for mon_datasource.moni_position
     *
     * @mbggenerated
     */
    public void setMoniPosition(String moniPosition) {
        this.moniPosition = moniPosition == null ? null : moniPosition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.description
     *
     * @return the value of mon_datasource.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.description
     *
     * @param description the value for mon_datasource.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.create_time
     *
     * @return the value of mon_datasource.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.create_time
     *
     * @param createTime the value for mon_datasource.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.create_user
     *
     * @return the value of mon_datasource.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.create_user
     *
     * @param createUser the value for mon_datasource.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.modify_time
     *
     * @return the value of mon_datasource.modify_time
     *
     * @mbggenerated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.modify_time
     *
     * @param modifyTime the value for mon_datasource.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_datasource.modify_user
     *
     * @return the value of mon_datasource.modify_user
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_datasource.modify_user
     *
     * @param modifyUser the value for mon_datasource.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }
}