package com.test.entity;

public class MonInfluxdb {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_influxdb.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_influxdb.config_name
     *
     * @mbggenerated
     */
    private String configName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_influxdb.config_url
     *
     * @mbggenerated
     */
    private String configUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_influxdb.config_user
     *
     * @mbggenerated
     */
    private String configUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_influxdb.config_pwd
     *
     * @mbggenerated
     */
    private String configPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_influxdb.db_name
     *
     * @mbggenerated
     */
    private String dbName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_influxdb.table_name
     *
     * @mbggenerated
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_influxdb.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_influxdb.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_influxdb.modify_user
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_influxdb.modify_time
     *
     * @mbggenerated
     */
    private String modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_influxdb.id
     *
     * @return the value of mon_influxdb.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_influxdb.id
     *
     * @param id the value for mon_influxdb.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_influxdb.config_name
     *
     * @return the value of mon_influxdb.config_name
     *
     * @mbggenerated
     */
    public String getConfigName() {
        return configName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_influxdb.config_name
     *
     * @param configName the value for mon_influxdb.config_name
     *
     * @mbggenerated
     */
    public void setConfigName(String configName) {
        this.configName = configName == null ? null : configName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_influxdb.config_url
     *
     * @return the value of mon_influxdb.config_url
     *
     * @mbggenerated
     */
    public String getConfigUrl() {
        return configUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_influxdb.config_url
     *
     * @param configUrl the value for mon_influxdb.config_url
     *
     * @mbggenerated
     */
    public void setConfigUrl(String configUrl) {
        this.configUrl = configUrl == null ? null : configUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_influxdb.config_user
     *
     * @return the value of mon_influxdb.config_user
     *
     * @mbggenerated
     */
    public String getConfigUser() {
        return configUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_influxdb.config_user
     *
     * @param configUser the value for mon_influxdb.config_user
     *
     * @mbggenerated
     */
    public void setConfigUser(String configUser) {
        this.configUser = configUser == null ? null : configUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_influxdb.config_pwd
     *
     * @return the value of mon_influxdb.config_pwd
     *
     * @mbggenerated
     */
    public String getConfigPwd() {
        return configPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_influxdb.config_pwd
     *
     * @param configPwd the value for mon_influxdb.config_pwd
     *
     * @mbggenerated
     */
    public void setConfigPwd(String configPwd) {
        this.configPwd = configPwd == null ? null : configPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_influxdb.db_name
     *
     * @return the value of mon_influxdb.db_name
     *
     * @mbggenerated
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_influxdb.db_name
     *
     * @param dbName the value for mon_influxdb.db_name
     *
     * @mbggenerated
     */
    public void setDbName(String dbName) {
        this.dbName = dbName == null ? null : dbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_influxdb.table_name
     *
     * @return the value of mon_influxdb.table_name
     *
     * @mbggenerated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_influxdb.table_name
     *
     * @param tableName the value for mon_influxdb.table_name
     *
     * @mbggenerated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_influxdb.create_time
     *
     * @return the value of mon_influxdb.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_influxdb.create_time
     *
     * @param createTime the value for mon_influxdb.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_influxdb.create_user
     *
     * @return the value of mon_influxdb.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_influxdb.create_user
     *
     * @param createUser the value for mon_influxdb.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_influxdb.modify_user
     *
     * @return the value of mon_influxdb.modify_user
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_influxdb.modify_user
     *
     * @param modifyUser the value for mon_influxdb.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_influxdb.modify_time
     *
     * @return the value of mon_influxdb.modify_time
     *
     * @mbggenerated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_influxdb.modify_time
     *
     * @param modifyTime the value for mon_influxdb.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }
}