package com.test.entity;

public class MonPoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.point_code
     *
     * @mbggenerated
     */
    private String pointCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.point_name
     *
     * @mbggenerated
     */
    private String pointName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.point_describe
     *
     * @mbggenerated
     */
    private String pointDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.type_code
     *
     * @mbggenerated
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.data_type
     *
     * @mbggenerated
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.data_unit
     *
     * @mbggenerated
     */
    private String dataUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.eq_code
     *
     * @mbggenerated
     */
    private String eqCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.eq_name
     *
     * @mbggenerated
     */
    private String eqName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.product_line
     *
     * @mbggenerated
     */
    private String productLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.product_process
     *
     * @mbggenerated
     */
    private String productProcess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.standard_value
     *
     * @mbggenerated
     */
    private String standardValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.upper_limit
     *
     * @mbggenerated
     */
    private String upperLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.lower_limit
     *
     * @mbggenerated
     */
    private String lowerLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.ds_code
     *
     * @mbggenerated
     */
    private String dsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.save_influxdb
     *
     * @mbggenerated
     */
    private String saveInfluxdb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.save_hive
     *
     * @mbggenerated
     */
    private String saveHive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.modify_time
     *
     * @mbggenerated
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_point.modify_user
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.id
     *
     * @return the value of mon_point.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.id
     *
     * @param id the value for mon_point.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.point_code
     *
     * @return the value of mon_point.point_code
     *
     * @mbggenerated
     */
    public String getPointCode() {
        return pointCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.point_code
     *
     * @param pointCode the value for mon_point.point_code
     *
     * @mbggenerated
     */
    public void setPointCode(String pointCode) {
        this.pointCode = pointCode == null ? null : pointCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.point_name
     *
     * @return the value of mon_point.point_name
     *
     * @mbggenerated
     */
    public String getPointName() {
        return pointName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.point_name
     *
     * @param pointName the value for mon_point.point_name
     *
     * @mbggenerated
     */
    public void setPointName(String pointName) {
        this.pointName = pointName == null ? null : pointName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.point_describe
     *
     * @return the value of mon_point.point_describe
     *
     * @mbggenerated
     */
    public String getPointDescribe() {
        return pointDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.point_describe
     *
     * @param pointDescribe the value for mon_point.point_describe
     *
     * @mbggenerated
     */
    public void setPointDescribe(String pointDescribe) {
        this.pointDescribe = pointDescribe == null ? null : pointDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.type_code
     *
     * @return the value of mon_point.type_code
     *
     * @mbggenerated
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.type_code
     *
     * @param typeCode the value for mon_point.type_code
     *
     * @mbggenerated
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.data_type
     *
     * @return the value of mon_point.data_type
     *
     * @mbggenerated
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.data_type
     *
     * @param dataType the value for mon_point.data_type
     *
     * @mbggenerated
     */
    public void setDataType(String dataType) {
        this.dataType = dataType == null ? null : dataType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.data_unit
     *
     * @return the value of mon_point.data_unit
     *
     * @mbggenerated
     */
    public String getDataUnit() {
        return dataUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.data_unit
     *
     * @param dataUnit the value for mon_point.data_unit
     *
     * @mbggenerated
     */
    public void setDataUnit(String dataUnit) {
        this.dataUnit = dataUnit == null ? null : dataUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.eq_code
     *
     * @return the value of mon_point.eq_code
     *
     * @mbggenerated
     */
    public String getEqCode() {
        return eqCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.eq_code
     *
     * @param eqCode the value for mon_point.eq_code
     *
     * @mbggenerated
     */
    public void setEqCode(String eqCode) {
        this.eqCode = eqCode == null ? null : eqCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.eq_name
     *
     * @return the value of mon_point.eq_name
     *
     * @mbggenerated
     */
    public String getEqName() {
        return eqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.eq_name
     *
     * @param eqName the value for mon_point.eq_name
     *
     * @mbggenerated
     */
    public void setEqName(String eqName) {
        this.eqName = eqName == null ? null : eqName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.location
     *
     * @return the value of mon_point.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.location
     *
     * @param location the value for mon_point.location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.product_line
     *
     * @return the value of mon_point.product_line
     *
     * @mbggenerated
     */
    public String getProductLine() {
        return productLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.product_line
     *
     * @param productLine the value for mon_point.product_line
     *
     * @mbggenerated
     */
    public void setProductLine(String productLine) {
        this.productLine = productLine == null ? null : productLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.product_process
     *
     * @return the value of mon_point.product_process
     *
     * @mbggenerated
     */
    public String getProductProcess() {
        return productProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.product_process
     *
     * @param productProcess the value for mon_point.product_process
     *
     * @mbggenerated
     */
    public void setProductProcess(String productProcess) {
        this.productProcess = productProcess == null ? null : productProcess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.standard_value
     *
     * @return the value of mon_point.standard_value
     *
     * @mbggenerated
     */
    public String getStandardValue() {
        return standardValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.standard_value
     *
     * @param standardValue the value for mon_point.standard_value
     *
     * @mbggenerated
     */
    public void setStandardValue(String standardValue) {
        this.standardValue = standardValue == null ? null : standardValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.upper_limit
     *
     * @return the value of mon_point.upper_limit
     *
     * @mbggenerated
     */
    public String getUpperLimit() {
        return upperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.upper_limit
     *
     * @param upperLimit the value for mon_point.upper_limit
     *
     * @mbggenerated
     */
    public void setUpperLimit(String upperLimit) {
        this.upperLimit = upperLimit == null ? null : upperLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.lower_limit
     *
     * @return the value of mon_point.lower_limit
     *
     * @mbggenerated
     */
    public String getLowerLimit() {
        return lowerLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.lower_limit
     *
     * @param lowerLimit the value for mon_point.lower_limit
     *
     * @mbggenerated
     */
    public void setLowerLimit(String lowerLimit) {
        this.lowerLimit = lowerLimit == null ? null : lowerLimit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.ds_code
     *
     * @return the value of mon_point.ds_code
     *
     * @mbggenerated
     */
    public String getDsCode() {
        return dsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.ds_code
     *
     * @param dsCode the value for mon_point.ds_code
     *
     * @mbggenerated
     */
    public void setDsCode(String dsCode) {
        this.dsCode = dsCode == null ? null : dsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.save_influxdb
     *
     * @return the value of mon_point.save_influxdb
     *
     * @mbggenerated
     */
    public String getSaveInfluxdb() {
        return saveInfluxdb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.save_influxdb
     *
     * @param saveInfluxdb the value for mon_point.save_influxdb
     *
     * @mbggenerated
     */
    public void setSaveInfluxdb(String saveInfluxdb) {
        this.saveInfluxdb = saveInfluxdb == null ? null : saveInfluxdb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.save_hive
     *
     * @return the value of mon_point.save_hive
     *
     * @mbggenerated
     */
    public String getSaveHive() {
        return saveHive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.save_hive
     *
     * @param saveHive the value for mon_point.save_hive
     *
     * @mbggenerated
     */
    public void setSaveHive(String saveHive) {
        this.saveHive = saveHive == null ? null : saveHive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.create_time
     *
     * @return the value of mon_point.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.create_time
     *
     * @param createTime the value for mon_point.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.create_user
     *
     * @return the value of mon_point.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.create_user
     *
     * @param createUser the value for mon_point.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.modify_time
     *
     * @return the value of mon_point.modify_time
     *
     * @mbggenerated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.modify_time
     *
     * @param modifyTime the value for mon_point.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_point.modify_user
     *
     * @return the value of mon_point.modify_user
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_point.modify_user
     *
     * @param modifyUser the value for mon_point.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }
}