package com.test.entity;

public class MonSvg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_svg.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_svg.product_line
     *
     * @mbggenerated
     */
    private String productLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_svg.svg_name
     *
     * @mbggenerated
     */
    private String svgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_svg.mon_description
     *
     * @mbggenerated
     */
    private String monDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_svg.svg_path
     *
     * @mbggenerated
     */
    private String svgPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_svg.svg_size
     *
     * @mbggenerated
     */
    private String svgSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_svg.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_svg.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_svg.modify_time
     *
     * @mbggenerated
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_svg.modify_user
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_svg.id
     *
     * @return the value of mon_svg.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_svg.id
     *
     * @param id the value for mon_svg.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_svg.product_line
     *
     * @return the value of mon_svg.product_line
     *
     * @mbggenerated
     */
    public String getProductLine() {
        return productLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_svg.product_line
     *
     * @param productLine the value for mon_svg.product_line
     *
     * @mbggenerated
     */
    public void setProductLine(String productLine) {
        this.productLine = productLine == null ? null : productLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_svg.svg_name
     *
     * @return the value of mon_svg.svg_name
     *
     * @mbggenerated
     */
    public String getSvgName() {
        return svgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_svg.svg_name
     *
     * @param svgName the value for mon_svg.svg_name
     *
     * @mbggenerated
     */
    public void setSvgName(String svgName) {
        this.svgName = svgName == null ? null : svgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_svg.mon_description
     *
     * @return the value of mon_svg.mon_description
     *
     * @mbggenerated
     */
    public String getMonDescription() {
        return monDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_svg.mon_description
     *
     * @param monDescription the value for mon_svg.mon_description
     *
     * @mbggenerated
     */
    public void setMonDescription(String monDescription) {
        this.monDescription = monDescription == null ? null : monDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_svg.svg_path
     *
     * @return the value of mon_svg.svg_path
     *
     * @mbggenerated
     */
    public String getSvgPath() {
        return svgPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_svg.svg_path
     *
     * @param svgPath the value for mon_svg.svg_path
     *
     * @mbggenerated
     */
    public void setSvgPath(String svgPath) {
        this.svgPath = svgPath == null ? null : svgPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_svg.svg_size
     *
     * @return the value of mon_svg.svg_size
     *
     * @mbggenerated
     */
    public String getSvgSize() {
        return svgSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_svg.svg_size
     *
     * @param svgSize the value for mon_svg.svg_size
     *
     * @mbggenerated
     */
    public void setSvgSize(String svgSize) {
        this.svgSize = svgSize == null ? null : svgSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_svg.create_time
     *
     * @return the value of mon_svg.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_svg.create_time
     *
     * @param createTime the value for mon_svg.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_svg.create_user
     *
     * @return the value of mon_svg.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_svg.create_user
     *
     * @param createUser the value for mon_svg.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_svg.modify_time
     *
     * @return the value of mon_svg.modify_time
     *
     * @mbggenerated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_svg.modify_time
     *
     * @param modifyTime the value for mon_svg.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_svg.modify_user
     *
     * @return the value of mon_svg.modify_user
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_svg.modify_user
     *
     * @param modifyUser the value for mon_svg.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }
}