package com.test.entity;

public class MonTree {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_tree.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_tree.node_code
     *
     * @mbggenerated
     */
    private String nodeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_tree.node_name
     *
     * @mbggenerated
     */
    private String nodeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_tree.node_type
     *
     * @mbggenerated
     */
    private String nodeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_tree.parent_node_code
     *
     * @mbggenerated
     */
    private String parentNodeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_tree.product_line
     *
     * @mbggenerated
     */
    private String productLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_tree.product_process
     *
     * @mbggenerated
     */
    private String productProcess;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_tree.eq_code
     *
     * @mbggenerated
     */
    private String eqCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_tree.eq_name
     *
     * @mbggenerated
     */
    private String eqName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_tree.point_code
     *
     * @mbggenerated
     */
    private String pointCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_tree.point_describe
     *
     * @mbggenerated
     */
    private String pointDescribe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_tree.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_tree.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_tree.modify_time
     *
     * @mbggenerated
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_tree.modify_user
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_tree.id
     *
     * @return the value of mon_tree.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_tree.id
     *
     * @param id the value for mon_tree.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_tree.node_code
     *
     * @return the value of mon_tree.node_code
     *
     * @mbggenerated
     */
    public String getNodeCode() {
        return nodeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_tree.node_code
     *
     * @param nodeCode the value for mon_tree.node_code
     *
     * @mbggenerated
     */
    public void setNodeCode(String nodeCode) {
        this.nodeCode = nodeCode == null ? null : nodeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_tree.node_name
     *
     * @return the value of mon_tree.node_name
     *
     * @mbggenerated
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_tree.node_name
     *
     * @param nodeName the value for mon_tree.node_name
     *
     * @mbggenerated
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_tree.node_type
     *
     * @return the value of mon_tree.node_type
     *
     * @mbggenerated
     */
    public String getNodeType() {
        return nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_tree.node_type
     *
     * @param nodeType the value for mon_tree.node_type
     *
     * @mbggenerated
     */
    public void setNodeType(String nodeType) {
        this.nodeType = nodeType == null ? null : nodeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_tree.parent_node_code
     *
     * @return the value of mon_tree.parent_node_code
     *
     * @mbggenerated
     */
    public String getParentNodeCode() {
        return parentNodeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_tree.parent_node_code
     *
     * @param parentNodeCode the value for mon_tree.parent_node_code
     *
     * @mbggenerated
     */
    public void setParentNodeCode(String parentNodeCode) {
        this.parentNodeCode = parentNodeCode == null ? null : parentNodeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_tree.product_line
     *
     * @return the value of mon_tree.product_line
     *
     * @mbggenerated
     */
    public String getProductLine() {
        return productLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_tree.product_line
     *
     * @param productLine the value for mon_tree.product_line
     *
     * @mbggenerated
     */
    public void setProductLine(String productLine) {
        this.productLine = productLine == null ? null : productLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_tree.product_process
     *
     * @return the value of mon_tree.product_process
     *
     * @mbggenerated
     */
    public String getProductProcess() {
        return productProcess;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_tree.product_process
     *
     * @param productProcess the value for mon_tree.product_process
     *
     * @mbggenerated
     */
    public void setProductProcess(String productProcess) {
        this.productProcess = productProcess == null ? null : productProcess.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_tree.eq_code
     *
     * @return the value of mon_tree.eq_code
     *
     * @mbggenerated
     */
    public String getEqCode() {
        return eqCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_tree.eq_code
     *
     * @param eqCode the value for mon_tree.eq_code
     *
     * @mbggenerated
     */
    public void setEqCode(String eqCode) {
        this.eqCode = eqCode == null ? null : eqCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_tree.eq_name
     *
     * @return the value of mon_tree.eq_name
     *
     * @mbggenerated
     */
    public String getEqName() {
        return eqName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_tree.eq_name
     *
     * @param eqName the value for mon_tree.eq_name
     *
     * @mbggenerated
     */
    public void setEqName(String eqName) {
        this.eqName = eqName == null ? null : eqName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_tree.point_code
     *
     * @return the value of mon_tree.point_code
     *
     * @mbggenerated
     */
    public String getPointCode() {
        return pointCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_tree.point_code
     *
     * @param pointCode the value for mon_tree.point_code
     *
     * @mbggenerated
     */
    public void setPointCode(String pointCode) {
        this.pointCode = pointCode == null ? null : pointCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_tree.point_describe
     *
     * @return the value of mon_tree.point_describe
     *
     * @mbggenerated
     */
    public String getPointDescribe() {
        return pointDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_tree.point_describe
     *
     * @param pointDescribe the value for mon_tree.point_describe
     *
     * @mbggenerated
     */
    public void setPointDescribe(String pointDescribe) {
        this.pointDescribe = pointDescribe == null ? null : pointDescribe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_tree.create_time
     *
     * @return the value of mon_tree.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_tree.create_time
     *
     * @param createTime the value for mon_tree.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_tree.create_user
     *
     * @return the value of mon_tree.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_tree.create_user
     *
     * @param createUser the value for mon_tree.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_tree.modify_time
     *
     * @return the value of mon_tree.modify_time
     *
     * @mbggenerated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_tree.modify_time
     *
     * @param modifyTime the value for mon_tree.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_tree.modify_user
     *
     * @return the value of mon_tree.modify_user
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_tree.modify_user
     *
     * @param modifyUser the value for mon_tree.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }
}