package com.test.entity;

public class MonThemeGroup_ {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group_.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group_.theme_id
     *
     * @mbggenerated
     */
    private String themeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group_.group_id
     *
     * @mbggenerated
     */
    private String groupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group_.point_code
     *
     * @mbggenerated
     */
    private String pointCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group_.point_name
     *
     * @mbggenerated
     */
    private String pointName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group_.image_type
     *
     * @mbggenerated
     */
    private String imageType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group_.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group_.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group_.modify_user
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group_.modify_time
     *
     * @mbggenerated
     */
    private String modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group_.id
     *
     * @return the value of mon_theme_group_.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group_.id
     *
     * @param id the value for mon_theme_group_.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group_.theme_id
     *
     * @return the value of mon_theme_group_.theme_id
     *
     * @mbggenerated
     */
    public String getThemeId() {
        return themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group_.theme_id
     *
     * @param themeId the value for mon_theme_group_.theme_id
     *
     * @mbggenerated
     */
    public void setThemeId(String themeId) {
        this.themeId = themeId == null ? null : themeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group_.group_id
     *
     * @return the value of mon_theme_group_.group_id
     *
     * @mbggenerated
     */
    public String getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group_.group_id
     *
     * @param groupId the value for mon_theme_group_.group_id
     *
     * @mbggenerated
     */
    public void setGroupId(String groupId) {
        this.groupId = groupId == null ? null : groupId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group_.point_code
     *
     * @return the value of mon_theme_group_.point_code
     *
     * @mbggenerated
     */
    public String getPointCode() {
        return pointCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group_.point_code
     *
     * @param pointCode the value for mon_theme_group_.point_code
     *
     * @mbggenerated
     */
    public void setPointCode(String pointCode) {
        this.pointCode = pointCode == null ? null : pointCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group_.point_name
     *
     * @return the value of mon_theme_group_.point_name
     *
     * @mbggenerated
     */
    public String getPointName() {
        return pointName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group_.point_name
     *
     * @param pointName the value for mon_theme_group_.point_name
     *
     * @mbggenerated
     */
    public void setPointName(String pointName) {
        this.pointName = pointName == null ? null : pointName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group_.image_type
     *
     * @return the value of mon_theme_group_.image_type
     *
     * @mbggenerated
     */
    public String getImageType() {
        return imageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group_.image_type
     *
     * @param imageType the value for mon_theme_group_.image_type
     *
     * @mbggenerated
     */
    public void setImageType(String imageType) {
        this.imageType = imageType == null ? null : imageType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group_.create_time
     *
     * @return the value of mon_theme_group_.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group_.create_time
     *
     * @param createTime the value for mon_theme_group_.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group_.create_user
     *
     * @return the value of mon_theme_group_.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group_.create_user
     *
     * @param createUser the value for mon_theme_group_.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group_.modify_user
     *
     * @return the value of mon_theme_group_.modify_user
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group_.modify_user
     *
     * @param modifyUser the value for mon_theme_group_.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group_.modify_time
     *
     * @return the value of mon_theme_group_.modify_time
     *
     * @mbggenerated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group_.modify_time
     *
     * @param modifyTime the value for mon_theme_group_.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }
}