package com.test.entity;

public class MonType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_type.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_type.type_code
     *
     * @mbggenerated
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_type.type_name
     *
     * @mbggenerated
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_type.type_order
     *
     * @mbggenerated
     */
    private String typeOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_type.type_specification
     *
     * @mbggenerated
     */
    private String typeSpecification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_type.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_type.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_type.modify_suer
     *
     * @mbggenerated
     */
    private String modifySuer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_type.modify_time
     *
     * @mbggenerated
     */
    private String modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_type.id
     *
     * @return the value of mon_type.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_type.id
     *
     * @param id the value for mon_type.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_type.type_code
     *
     * @return the value of mon_type.type_code
     *
     * @mbggenerated
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_type.type_code
     *
     * @param typeCode the value for mon_type.type_code
     *
     * @mbggenerated
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_type.type_name
     *
     * @return the value of mon_type.type_name
     *
     * @mbggenerated
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_type.type_name
     *
     * @param typeName the value for mon_type.type_name
     *
     * @mbggenerated
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_type.type_order
     *
     * @return the value of mon_type.type_order
     *
     * @mbggenerated
     */
    public String getTypeOrder() {
        return typeOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_type.type_order
     *
     * @param typeOrder the value for mon_type.type_order
     *
     * @mbggenerated
     */
    public void setTypeOrder(String typeOrder) {
        this.typeOrder = typeOrder == null ? null : typeOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_type.type_specification
     *
     * @return the value of mon_type.type_specification
     *
     * @mbggenerated
     */
    public String getTypeSpecification() {
        return typeSpecification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_type.type_specification
     *
     * @param typeSpecification the value for mon_type.type_specification
     *
     * @mbggenerated
     */
    public void setTypeSpecification(String typeSpecification) {
        this.typeSpecification = typeSpecification == null ? null : typeSpecification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_type.create_time
     *
     * @return the value of mon_type.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_type.create_time
     *
     * @param createTime the value for mon_type.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_type.create_user
     *
     * @return the value of mon_type.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_type.create_user
     *
     * @param createUser the value for mon_type.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_type.modify_suer
     *
     * @return the value of mon_type.modify_suer
     *
     * @mbggenerated
     */
    public String getModifySuer() {
        return modifySuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_type.modify_suer
     *
     * @param modifySuer the value for mon_type.modify_suer
     *
     * @mbggenerated
     */
    public void setModifySuer(String modifySuer) {
        this.modifySuer = modifySuer == null ? null : modifySuer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_type.modify_time
     *
     * @return the value of mon_type.modify_time
     *
     * @mbggenerated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_type.modify_time
     *
     * @param modifyTime the value for mon_type.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }
}