package com.test.entity;

public class MonThemeGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group.theme_id
     *
     * @mbggenerated
     */
    private String themeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group.group_name
     *
     * @mbggenerated
     */
    private String groupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group.time_rage
     *
     * @mbggenerated
     */
    private String timeRage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group.time_space
     *
     * @mbggenerated
     */
    private String timeSpace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group.space_unit
     *
     * @mbggenerated
     */
    private String spaceUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group.x_axis
     *
     * @mbggenerated
     */
    private String xAxis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group.complete_method
     *
     * @mbggenerated
     */
    private String completeMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group.group_description
     *
     * @mbggenerated
     */
    private String groupDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group.modify_user
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme_group.modify_time
     *
     * @mbggenerated
     */
    private String modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group.id
     *
     * @return the value of mon_theme_group.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group.id
     *
     * @param id the value for mon_theme_group.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group.theme_id
     *
     * @return the value of mon_theme_group.theme_id
     *
     * @mbggenerated
     */
    public String getThemeId() {
        return themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group.theme_id
     *
     * @param themeId the value for mon_theme_group.theme_id
     *
     * @mbggenerated
     */
    public void setThemeId(String themeId) {
        this.themeId = themeId == null ? null : themeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group.group_name
     *
     * @return the value of mon_theme_group.group_name
     *
     * @mbggenerated
     */
    public String getGroupName() {
        return groupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group.group_name
     *
     * @param groupName the value for mon_theme_group.group_name
     *
     * @mbggenerated
     */
    public void setGroupName(String groupName) {
        this.groupName = groupName == null ? null : groupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group.time_rage
     *
     * @return the value of mon_theme_group.time_rage
     *
     * @mbggenerated
     */
    public String getTimeRage() {
        return timeRage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group.time_rage
     *
     * @param timeRage the value for mon_theme_group.time_rage
     *
     * @mbggenerated
     */
    public void setTimeRage(String timeRage) {
        this.timeRage = timeRage == null ? null : timeRage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group.time_space
     *
     * @return the value of mon_theme_group.time_space
     *
     * @mbggenerated
     */
    public String getTimeSpace() {
        return timeSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group.time_space
     *
     * @param timeSpace the value for mon_theme_group.time_space
     *
     * @mbggenerated
     */
    public void setTimeSpace(String timeSpace) {
        this.timeSpace = timeSpace == null ? null : timeSpace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group.space_unit
     *
     * @return the value of mon_theme_group.space_unit
     *
     * @mbggenerated
     */
    public String getSpaceUnit() {
        return spaceUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group.space_unit
     *
     * @param spaceUnit the value for mon_theme_group.space_unit
     *
     * @mbggenerated
     */
    public void setSpaceUnit(String spaceUnit) {
        this.spaceUnit = spaceUnit == null ? null : spaceUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group.x_axis
     *
     * @return the value of mon_theme_group.x_axis
     *
     * @mbggenerated
     */
    public String getxAxis() {
        return xAxis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group.x_axis
     *
     * @param xAxis the value for mon_theme_group.x_axis
     *
     * @mbggenerated
     */
    public void setxAxis(String xAxis) {
        this.xAxis = xAxis == null ? null : xAxis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group.complete_method
     *
     * @return the value of mon_theme_group.complete_method
     *
     * @mbggenerated
     */
    public String getCompleteMethod() {
        return completeMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group.complete_method
     *
     * @param completeMethod the value for mon_theme_group.complete_method
     *
     * @mbggenerated
     */
    public void setCompleteMethod(String completeMethod) {
        this.completeMethod = completeMethod == null ? null : completeMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group.group_description
     *
     * @return the value of mon_theme_group.group_description
     *
     * @mbggenerated
     */
    public String getGroupDescription() {
        return groupDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group.group_description
     *
     * @param groupDescription the value for mon_theme_group.group_description
     *
     * @mbggenerated
     */
    public void setGroupDescription(String groupDescription) {
        this.groupDescription = groupDescription == null ? null : groupDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group.create_time
     *
     * @return the value of mon_theme_group.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group.create_time
     *
     * @param createTime the value for mon_theme_group.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group.create_user
     *
     * @return the value of mon_theme_group.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group.create_user
     *
     * @param createUser the value for mon_theme_group.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group.modify_user
     *
     * @return the value of mon_theme_group.modify_user
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group.modify_user
     *
     * @param modifyUser the value for mon_theme_group.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme_group.modify_time
     *
     * @return the value of mon_theme_group.modify_time
     *
     * @mbggenerated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme_group.modify_time
     *
     * @param modifyTime the value for mon_theme_group.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }
}