package com.test.entity;

public class MonTheme {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme.product_line
     *
     * @mbggenerated
     */
    private String productLine;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme.theme_code
     *
     * @mbggenerated
     */
    private String themeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme.theme_name
     *
     * @mbggenerated
     */
    private String themeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme.parent_theme_code
     *
     * @mbggenerated
     */
    private String parentThemeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme.modify_time
     *
     * @mbggenerated
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_theme.modify_user
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme.id
     *
     * @return the value of mon_theme.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme.id
     *
     * @param id the value for mon_theme.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme.product_line
     *
     * @return the value of mon_theme.product_line
     *
     * @mbggenerated
     */
    public String getProductLine() {
        return productLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme.product_line
     *
     * @param productLine the value for mon_theme.product_line
     *
     * @mbggenerated
     */
    public void setProductLine(String productLine) {
        this.productLine = productLine == null ? null : productLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme.theme_code
     *
     * @return the value of mon_theme.theme_code
     *
     * @mbggenerated
     */
    public String getThemeCode() {
        return themeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme.theme_code
     *
     * @param themeCode the value for mon_theme.theme_code
     *
     * @mbggenerated
     */
    public void setThemeCode(String themeCode) {
        this.themeCode = themeCode == null ? null : themeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme.theme_name
     *
     * @return the value of mon_theme.theme_name
     *
     * @mbggenerated
     */
    public String getThemeName() {
        return themeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme.theme_name
     *
     * @param themeName the value for mon_theme.theme_name
     *
     * @mbggenerated
     */
    public void setThemeName(String themeName) {
        this.themeName = themeName == null ? null : themeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme.parent_theme_code
     *
     * @return the value of mon_theme.parent_theme_code
     *
     * @mbggenerated
     */
    public String getParentThemeCode() {
        return parentThemeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme.parent_theme_code
     *
     * @param parentThemeCode the value for mon_theme.parent_theme_code
     *
     * @mbggenerated
     */
    public void setParentThemeCode(String parentThemeCode) {
        this.parentThemeCode = parentThemeCode == null ? null : parentThemeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme.create_time
     *
     * @return the value of mon_theme.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme.create_time
     *
     * @param createTime the value for mon_theme.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme.create_user
     *
     * @return the value of mon_theme.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme.create_user
     *
     * @param createUser the value for mon_theme.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme.modify_time
     *
     * @return the value of mon_theme.modify_time
     *
     * @mbggenerated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme.modify_time
     *
     * @param modifyTime the value for mon_theme.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_theme.modify_user
     *
     * @return the value of mon_theme.modify_user
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_theme.modify_user
     *
     * @param modifyUser the value for mon_theme.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }
}