package com.test.entity;

public class MonUnit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_unit.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_unit.type_code
     *
     * @mbggenerated
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_unit.unit_name
     *
     * @mbggenerated
     */
    private String unitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_unit.aggregate_type
     *
     * @mbggenerated
     */
    private String aggregateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_unit.create_time
     *
     * @mbggenerated
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_unit.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_unit.modify_time
     *
     * @mbggenerated
     */
    private String modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mon_unit.modify_user
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_unit.id
     *
     * @return the value of mon_unit.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_unit.id
     *
     * @param id the value for mon_unit.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_unit.type_code
     *
     * @return the value of mon_unit.type_code
     *
     * @mbggenerated
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_unit.type_code
     *
     * @param typeCode the value for mon_unit.type_code
     *
     * @mbggenerated
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_unit.unit_name
     *
     * @return the value of mon_unit.unit_name
     *
     * @mbggenerated
     */
    public String getUnitName() {
        return unitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_unit.unit_name
     *
     * @param unitName the value for mon_unit.unit_name
     *
     * @mbggenerated
     */
    public void setUnitName(String unitName) {
        this.unitName = unitName == null ? null : unitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_unit.aggregate_type
     *
     * @return the value of mon_unit.aggregate_type
     *
     * @mbggenerated
     */
    public String getAggregateType() {
        return aggregateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_unit.aggregate_type
     *
     * @param aggregateType the value for mon_unit.aggregate_type
     *
     * @mbggenerated
     */
    public void setAggregateType(String aggregateType) {
        this.aggregateType = aggregateType == null ? null : aggregateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_unit.create_time
     *
     * @return the value of mon_unit.create_time
     *
     * @mbggenerated
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_unit.create_time
     *
     * @param createTime the value for mon_unit.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_unit.create_user
     *
     * @return the value of mon_unit.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_unit.create_user
     *
     * @param createUser the value for mon_unit.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_unit.modify_time
     *
     * @return the value of mon_unit.modify_time
     *
     * @mbggenerated
     */
    public String getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_unit.modify_time
     *
     * @param modifyTime the value for mon_unit.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(String modifyTime) {
        this.modifyTime = modifyTime == null ? null : modifyTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mon_unit.modify_user
     *
     * @return the value of mon_unit.modify_user
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mon_unit.modify_user
     *
     * @param modifyUser the value for mon_unit.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser == null ? null : modifyUser.trim();
    }
}