package com.test.dao;

import com.test.entity.MonDatasource;
import org.springframework.stereotype.Repository;

@Repository
public interface MonDatasourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_datasource
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_datasource
     *
     * @mbggenerated
     */
    int insert(MonDatasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_datasource
     *
     * @mbggenerated
     */
    int insertSelective(MonDatasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_datasource
     *
     * @mbggenerated
     */
    MonDatasource selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_datasource
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MonDatasource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_datasource
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MonDatasource record);
}