package com.test.dao;

import com.test.entity.MonInfluxdb;
import org.springframework.stereotype.Repository;

@Repository
public interface MonInfluxdbMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_influxdb
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_influxdb
     *
     * @mbggenerated
     */
    int insert(MonInfluxdb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_influxdb
     *
     * @mbggenerated
     */
    int insertSelective(MonInfluxdb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_influxdb
     *
     * @mbggenerated
     */
    MonInfluxdb selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_influxdb
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MonInfluxdb record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_influxdb
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MonInfluxdb record);
}