package com.test.dao;

import com.test.entity.MonType;
import org.springframework.stereotype.Repository;

@Repository
public interface MonTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_type
     *
     * @mbggenerated
     */
    int insert(MonType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_type
     *
     * @mbggenerated
     */
    int insertSelective(MonType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_type
     *
     * @mbggenerated
     */
    MonType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MonType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MonType record);
}