package com.test.dao;

import com.test.entity.MonThemeGroup;
import org.springframework.stereotype.Repository;

@Repository
public interface MonThemeGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_theme_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_theme_group
     *
     * @mbggenerated
     */
    int insert(MonThemeGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_theme_group
     *
     * @mbggenerated
     */
    int insertSelective(MonThemeGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_theme_group
     *
     * @mbggenerated
     */
    MonThemeGroup selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_theme_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MonThemeGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_theme_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MonThemeGroup record);
}