package com.test.dao;

import com.test.entity.MonTheme;
import org.springframework.stereotype.Repository;

@Repository
public interface MonThemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_theme
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_theme
     *
     * @mbggenerated
     */
    int insert(MonTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_theme
     *
     * @mbggenerated
     */
    int insertSelective(MonTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_theme
     *
     * @mbggenerated
     */
    MonTheme selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_theme
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MonTheme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_theme
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MonTheme record);
}