package com.test.dao;

import com.test.entity.MonUnit;
import org.apache.ibatis.annotations.Select;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface MonUnitMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_unit
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_unit
     *
     * @mbggenerated
     */
    int insert(MonUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_unit
     *
     * @mbggenerated
     */
    int insertSelective(MonUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_unit
     *
     * @mbggenerated
     */
    MonUnit selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_unit
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MonUnit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mon_unit
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MonUnit record);

    @Select("select * from mon_unit")
    List<MonUnit> getList();
}